# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matern <- function(d, sigma2, phi, nu) {
    .Call(`_GoogleCar_matern`, d, sigma2, phi, nu)
}

matern_stx_cpp <- function(sigma2, phi, rho, psi, nu, t1, t2, X1, X2, locs1, locs2, sq = FALSE) {
    .Call(`_GoogleCar_matern_stx_cpp`, sigma2, phi, rho, psi, nu, t1, t2, X1, X2, locs1, locs2, sq)
}

matern_st_cpp <- function(sigma2, phi, rho, nu, t1, t2, locs1, locs2, sq = FALSE) {
    .Call(`_GoogleCar_matern_st_cpp`, sigma2, phi, rho, nu, t1, t2, locs1, locs2, sq)
}

matern_s_cpp <- function(sigma2, phi, nu, locs1, locs2, sq = FALSE) {
    .Call(`_GoogleCar_matern_s_cpp`, sigma2, phi, nu, locs1, locs2, sq)
}

krig_STX_cpp <- function(par, S1, t1, X1, S2, t2, X2, Y2, Xb1, Xb2) {
    .Call(`_GoogleCar_krig_STX_cpp`, par, S1, t1, X1, S2, t2, X2, Y2, Xb1, Xb2)
}

